const data = [
  {
    product_name: "Water",
    website_url: "http://poseidon.trident.com",
    website_username: "Poseidon16700",
    company_name: "Sea",
    license_key: "abcd1234",
    purchase_date: "2020-12-11",
    expiration_date: null,
    renew_date: null,
    amount: "1241.00",
    invoice: "/software/invoices/Maledicent_Ei_Luna.pdf",
    file: "/software/files/Reddcraft.png",
    status: 0,
  },
  {
    product_name: "Fire",
    website_url: "http://hephaestus.labrys.com",
    website_username: "metalworkmason",
    company_name: "Labrys",
    license_key: "frgn234532",
    purchase_date: "2022-05-02",
    expiration_date: "2022-06-01",
    renew_date: null,
    amount: "48920.00",
    invoice: "/software/invoices/1_The_Fall_of_Reach.pdf",
    file: "/software/files/GOJO_SATORU.png",
    status: -1,
  },
  {
    product_name: "Kaminari",
    website_url: "http://zeusisanass.bolt.com",
    website_username: "zeus",
    company_name: "Bolt Inc.",
    license_key: "cllm3504",
    purchase_date: "2013-02-23",
    expiration_date: "2022-07-10",
    renew_date: null,
    amount: "42999.00",
    invoice:
      "/software/invoices/Assimil_with_Ease_1_Catherine_Garnier_Mori_Toshiko_-_Japanese_with_Eas_cVfE1Dh.pdf",
    file: "/software/files/I_AM_THE_ONE_The_THREE_actually.png",
    status: 4,
  },
  {
    product_name: "Water",
    website_url: "http://poseidon.trident.com",
    website_username: "Poseidon16700",
    company_name: "Sea",
    license_key: "abcd1234",
    purchase_date: "2020-12-11",
    expiration_date: null,
    renew_date: null,
    amount: "1241.00",
    invoice: "/software/invoices/Maledicent_Ei_Luna.pdf",
    file: "/software/files/Reddcraft.png",
    status: 0,
  },
  {
    product_name: "Fire",
    website_url: "http://hephaestus.labrys.com",
    website_username: "metalworkmason",
    company_name: "Labrys",
    license_key: "frgn234532",
    purchase_date: "2022-05-02",
    expiration_date: "2022-06-01",
    renew_date: null,
    amount: "48920.00",
    invoice: "/software/invoices/1_The_Fall_of_Reach.pdf",
    file: "/software/files/GOJO_SATORU.png",
    status: -1,
  },
  {
    product_name: "Kaminari",
    website_url: "http://zeusisanass.bolt.com",
    website_username: "zeus",
    company_name: "Bolt Inc.",
    license_key: "cllm3504",
    purchase_date: "2013-02-23",
    expiration_date: "2022-07-10",
    renew_date: null,
    amount: "42999.00",
    invoice:
      "/software/invoices/Assimil_with_Ease_1_Catherine_Garnier_Mori_Toshiko_-_Japanese_with_Eas_cVfE1Dh.pdf",
    file: "/software/files/I_AM_THE_ONE_The_THREE_actually.png",
    status: 4,
  },
  {
    product_name: "Water",
    website_url: "http://poseidon.trident.com",
    website_username: "Poseidon16700",
    company_name: "Sea",
    license_key: "abcd1234",
    purchase_date: "2020-12-11",
    expiration_date: null,
    renew_date: null,
    amount: "1241.00",
    invoice: "/software/invoices/Maledicent_Ei_Luna.pdf",
    file: "/software/files/Reddcraft.png",
    status: 0,
  },
  {
    product_name: "Fire",
    website_url: "http://hephaestus.labrys.com",
    website_username: "metalworkmason",
    company_name: "Labrys",
    license_key: "frgn234532",
    purchase_date: "2022-05-02",
    expiration_date: "2022-06-01",
    renew_date: null,
    amount: "48920.00",
    invoice: "/software/invoices/1_The_Fall_of_Reach.pdf",
    file: "/software/files/GOJO_SATORU.png",
    status: -1,
  },
  {
    product_name: "Kaminari",
    website_url: "http://zeusisanass.bolt.com",
    website_username: "zeus",
    company_name: "Bolt Inc.",
    license_key: "cllm3504",
    purchase_date: "2013-02-23",
    expiration_date: "2022-07-10",
    renew_date: null,
    amount: "42999.00",
    invoice:
      "/software/invoices/Assimil_with_Ease_1_Catherine_Garnier_Mori_Toshiko_-_Japanese_with_Eas_cVfE1Dh.pdf",
    file: "/software/files/I_AM_THE_ONE_The_THREE_actually.png",
    status: 4,
  },
];
export default data;